using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;

namespace _99bugs
{
    [Activity(Label = "SecondActivity")]
    public class SecondActivity : Activity
    {

        int bugs = 99;
        
        protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);

            SetContentView(Resource.Layout.Second);
            
            int bugsRand = Intent.Extras.GetInt(FirstActivity.EXTRA_BUGS);
            
            var bugLbl = FindViewById<TextView>(Resource.Id.bugLbl);
            
            //this is the number that is generated by the button
            bugLbl.Text = bugsRand.ToString();
             
            Button patchBtn = FindViewById<Button>(Resource.Id.patchBtn);
            patchBtn.Click += delegate
            {
                
                var first = new Intent(this, typeof(FirstActivity));
                //creating the new number of bugs hehehhe
                int total = BugNum(bugsRand);
                first.PutExtra(FirstActivity.EXTRA_NEW, total);
                SetResult(Result.Ok, first);
                Finish();
            };
        }


        //checking whether the number passed from hte first activity is even
        //if it is it adds to the num of bugs, if its odd it subtracts
        protected int BugNum(int i)
        {
            int b = i % 2;

            if (b == 0)
            {
                bugs += i; 
            }
            else
            {
                bugs -= i;
            }
            return bugs;
        }

    }
}